package vehicle

import (
	"github.com/HyperloopUPV-H8/h9-backend/pkg/transport/packet/protection"

	"github.com/HyperloopUPV-H8/h9-backend/internal/update_factory"
	"github.com/HyperloopUPV-H8/h9-backend/pkg/abstraction"
	"github.com/rs/zerolog"
)

// Vehicle is the main abstraction that coordinates the backend modules.
// It receives its modules and once it is ready, the vehicle manages the flow of
// information between them, converting events generated by one module to the specific
// input for another one.
type Vehicle struct {
	transport     abstraction.Transport
	logger        abstraction.Logger
	updateFactory *update_factory.UpdateFactory
	idToBoardName map[abstraction.PacketId]string

	trace zerolog.Logger
}

func (vehicle *Vehicle) notifyError(name string, err error) {
	packet := protection.NewPacket(1666, protection.FaultSeverity)
	packet.Kind = protection.ErrorHandlerKind
	packet.Name = name
	packet.Timestamp = protection.NowTimestamp()
	packet.Type = protection.IntType
	packet.Data = &protection.ErrorHandler{
		Error: err.Error(),
	}
}
