package vehicle

import (
	"github.com/HyperloopUPV-H8/h9-backend/pkg/abstraction"
	"github.com/HyperloopUPV-H8/h9-backend/pkg/store"
	"github.com/rs/zerolog"
)

// Vehicle is the main abstraction that coordinates the backend modules.
// It receives its modules and once it is ready, the vehicle manages the flow of
// information between them, converting events generated by one module to the specific
// input for another one.
type Vehicle struct {
	transport     abstraction.Transport
	logger        abstraction.Logger
	storage       *store.Store
	idToBoardName map[abstraction.PacketId]string

	trace zerolog.Logger
}

func (vehicle *Vehicle) notifyError(name string, err error) {
	vehicle.trace.Warn().Type("Notification Error", name).Err(err).Msg("notification error")
}
