# Hyperloop UPV Hypervisor Configuration File


# Control Station general configuration
[app]
addr = "0.0.0.0:80" # Where app will listen for incoming connections
static_path = "./hv-front" 

# Vehicle Configuration
[vehicle]
boards = [ "HVSCU"]

# ADJ (Architecture Description JSON) Configuration
[adj]
branch = "Test_Hypervisor" # Leave blank when using ADJ as a submodule (like this: "")

# Network Configuration
[network]
manual = false # Manual network device selection
dev_mode = false # Enable development mode features

# Logger Configuration
[logging]
time_unit = "us"      # Time unit for log timestamps (ns, us, ms, s)  Default: ns
logging_path = "."    # Absolute path of the logger

