# Hyperloop UPV Hypervisor Configuration File


# Hypervisor Station general configuration
[app]
addr = "0.0.0.0:80" # Where app will listen for incoming connections
hypervisor_addr = "192.168.0.23" # IP address of the Hypervisor (where the backend will send commands and receive telemetry data)
static_path = "./frontend/dist" # Path to the frontend static files (relative to the backend/cmd directory)
periodic_interval = 250 # Interval in milliseconds for periodic tasks (like fetching telemetry data)

# ADJ (Architecture Description JSON) Configuration
[adj]
branch = "Test_Hypervisor" # Leave blank when using ADJ as a submodule (like this: "")

# Network Configuration
[network]
dev_mode = false # Enable development mode features
sniffer_ips = [ "192.168.0.9" , "192.168.0.10" ] # List of IP addresses of devices to sniff on the network  (used when having multiple backend)

# Logger Configuration
[logging]
time_unit = "us"      # Time unit for log timestamps (ns, us, ms, s)  Default: ns
logging_path = "."    # Absolute path of the logger

