package store

import (
	"sync"

	"github.com/HyperloopUPV-H8/h9-backend/pkg/transport/packet/data"
	"github.com/rs/zerolog"
)

type Store struct {

	// Logger for the store
	trace zerolog.Logger

	// Base of the measurements, base info that will be send to the clients during the initial connection contains data like units, board ip,
	measuramentBase MeasurementBases

	// Measurements required to monitor grouped by their board id and packet id
	boardsIDEquivalences BoardIDEquivalences
	// packetIDEquivalence equivalences of a packet ID to measurement autogenerated ID using mesurementID. packetIDEquivalences also works as a filter to know which packets contain measurements to monitor and its corresponding autogenerate IDs
	packetIDEquivalences PacketIDEquivalences

	// Latest measurement updates snapshot will send by worker to the frontend each interval
	updates MeasurementUpdates

	// Mutex for ensuring to avoid race conditions while updating a variable
	mu sync.Mutex

	// Next autogenerate ID for measurements.
	// Used to assing each measurement a unique ID to transmit to the frontend to reduce data size, will be send during the initial connection as part of the measurement base
	nextID AutogenerateID
}

// AutogenerateID is the internal identifier for each measurement in the store and is common within the frontend and backend. Defined as int32 to reduce data size during transmission.
type AutogenerateID int32
type ValueUpdate string

// Each update contains a map of measurement updates
type MeasurementUpdates map[AutogenerateID]ValueUpdate

// Base information for each measurement
type MeasurementBase struct {
	MeasuramentID string   `json:"measurement_id"`
	BoardID       string   `json:"board_id"`
	DisplayUnits  string   `json:"display_units"`
	Type          string   `json:"type"`
	EnumValues    []string `json:"enumValues,omitempty"`
}

// Base map of measurements
type MeasurementBases map[AutogenerateID]MeasurementBase

// BoardID and PacketID would normally be uint, however we keep them as an string because improves the process of writtin JSON files
type BoardIDString string
type PacketIDString string

// data.ValueName is the same for packets that the measurament id

// Hipervisor monitor for unmarshalling JSON
type HypervisorMonitoring map[BoardIDString]map[PacketIDString][]data.ValueName
type BoardIDEquivalences map[BoardIDString]map[PacketIDString]map[data.ValueName]AutogenerateID

type PacketIDEquivalences map[PacketIDString]map[data.ValueName]AutogenerateID
