// Methods to manage the status of the storage, add and Snapshot and Reset
package store

import (
	"fmt"

	"github.com/Hyperloop-UPV/Hypervisor/pkg/transport/packet/data"
)

func (s *Store) AddUpdate(packet *data.Packet) {

	// if the measurement is not found we do not update the state
	measuraments, ok := s.packetIDEquivalences[PacketIDString(fmt.Sprintf("%d", packet.Id()))]
	if !ok {
		return
	}

	// get measuraments
	packetValues := packet.GetValues()

	// Block to update
	s.mu.Lock()
	defer s.mu.Unlock()

	for measure, autogeneratedID := range measuraments {

		value, exists := packetValues[measure]
		if !exists || value == nil {
			s.trace.Warn().
				Str("measurement", string(measure)).
				Msg("measurement not found in packetValues")
			continue
		}

		s.updates[autogeneratedID] = ValueUpdate(value.String())
	}
}

func (s *Store) SnapshotAndReset() MeasurementUpdates {

	s.mu.Lock()
	defer s.mu.Unlock()

	// copy everything
	snapshot := make(MeasurementUpdates, len(s.updates))
	for k, v := range s.updates {
		snapshot[k] = v
	}

	// restar uptades
	s.updates = make(MeasurementUpdates)

	return snapshot
}
