// Methods to manage the status of the storage, add and Snapshot and Reset
package store

import (
	"fmt"

	"github.comHyperloop-UPV/Hypervisor/pkg/transport/packet/data"
)

func (s *Store) AddUpdate(packet *data.Packet) {

	// if the measurement is not found we do not update the state
	measuraments, ok := s.packetIDEquivalences[PacketIDString(fmt.Sprintf("%d", packet.Id()))]
	if !ok {
		return
	}

	// get measuraments
	packetValues := packet.GetValues()

	// Block to update
	s.mu.Lock()
	defer s.mu.Unlock()

	// Update updates with the measurements defined in monitoring
	for measure, autogeneratedID := range measuraments {

		// Creates updates or overwrites it
		s.updates[autogeneratedID] = ValueUpdate(packetValues[measure].String())
	}

}

func (s *Store) SnapshotAndReset() MeasurementUpdates {

	s.mu.Lock()
	defer s.mu.Unlock()

	// copy everything
	snapshot := make(MeasurementUpdates, len(s.updates))
	for k, v := range s.updates {
		snapshot[k] = v
	}

	// restar uptades
	s.updates = make(MeasurementUpdates)

	return snapshot
}
